version: '3'

services:
  server:
    container_name: node-app
    restart: always
    build: .
    ports:
      - "3002:3002"
    links: 
      - mongo
  mongo:
    container_name: mongodatabase
    image: mongo
    ports: 
      - "27017:27017"